### PR TITLE
Nova 4 Support

### LINKED ISSUE #36: Nova 4 support

### PR DESCRIPTION
**Pull request by bashgeek**
This modifies the code to work with Nova 4. Fixes #36 

IMPORTANT: Because of the heavy changes from Nova 3 to 4 (i.e. Vue 1 -> 3, Vue Router -> Inertia) this will break compatibility with Nova 3, so maybe release a separate major version for this.

Besides the updates to the new environment this also includes:
- Use now included Heroicon for move handle
- Change general style to match Nova 4
- Making sure it works fine responsively
- Making sure it works fine in dark-mode

See it in action below:
CleanShot 2022-04-10 at 15 30 48

Let me know if breaks anything else.

### CODE REVIEW

**Comment by bashgeek** [comment]
@dillingham Don't want to seem impatient here, just gonna ask now to avoid disappointment down the line: Are you still maintaining this repo and plan to merge and publish this in the near future or should we rather move on with a fork? Thanks a lot!

**Comment by SupchickCode** [comment]
Thx u a lot it works fine !

**Comment by bashgeek** [comment]
Seems like this is kind of abandoned for now. If anybody is looking for a working Nova 4 version, here is our fork with this PR applied and used in production by us already:
https://github.com/blendbyte/nova-items-field

**Comment by lucianholt97** [comment]
Would be very happy if you can review this PR @dillingham? Thanks in advance!

**Pull request closed without merging**
